#!/bin/zsh

CMDNAME=`basename $0`

# 引数を使用する
while getopts u OPT
do
  case $OPT in
    "u" ) FLG_UP="TRUE" ;;
      * ) echo "Usage: $CMDNAME [-u]" 1>&2
          exit 1 ;;
  esac
done

shift `expr $OPTIND - 1`

# 実行時に指定された引数の数、つまり変数 $# の値が 1 でなければエラー終了。
if [ $# -ne 1 ]; then
  echo "指定された引数は$#個です。" 1>&2
  echo "実行するには1個の引数が必要です。" 1>&2
  exit 1
fi

# setting
LOCAL_DIR=$HOME/workspace/$1/
REMOTE_DIR="~/workspace/"
HOST=$1
USER="yonezu"

# upload
if [ "$FLG_UP" = "TRUE" ]; then
  rsync -auvzCP --delete --log-file=$HOME/log/rsync \
  --filter=":- .gitignore" --exclude='.*.sw*' --exclude='tmp/*' \
  $LOCAL_DIR $USER@$HOST:$REMOTE_DIR
  exit 0
fi

# test
rsync -auvznCP --delete --log-file=$HOME/log/rsync \
--filter=":- .gitignore" --exclude='.*.sw*' --exclude='tmp/*' \
$LOCAL_DIR $USER@$HOST:$REMOTE_DIR
exit 0
